Refresh GitLab script template

diff --git a/bin/archive-gitlab b/bin/archive-gitlab
--- a/bin/archive-gitlab
+++ b/bin/archive-gitlab
@@ -10,64 +10,112 @@
 #   $ SALSA_TOKEN=xxx ./bin/archive-gitlab project
 #
 # Requirements:
-#   # apt update && apt install --yes --no-install-recommends curl ca-certificates
+#   # apt-get update && apt-get install --yes --no-install-recommends curl ca-certificates
 #   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 ## Quit on error
 set -e
+#set -eo pipefail
+
+## DEBUG
+#set -x
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 packages=$*
 
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+## GitLab API Key
+##   REF: https://gitlab.com/profile/personal_access_tokens
+##   echo 'SALSA_TOKEN="12345678901234567890"' > ${APIFILE} # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
+APIFILE="./.gitlab-token"
 
-check_return_code() {
-  code=$?
-  if [ ${code} -eq 0 ]; then
-    echo "[+] ${package} archived ~ https://gitlab.com/kalilinux/packages/${package}"
-  else
-    echo "[-] ERROR: Something went wrong with archival of ${package}: ${code} ~ https://gitlab.com/kalilinux/packages/${package}" >&2
-  fi
-}
+## What (sub-)group to search
+groupname="kalilinux/packages"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-source .gitlab-token 2>/dev/null \
-  || true
-
-if [ -z "${SALSA_TOKEN}" ]; then
-  echo "[-] ERROR: You are missing: $( pwd )/.gitlab-token" >&2
-  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
-  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/.gitlab-token" >&2
-  exit 1
-fi
-
-if [ -z "${packages}" ]; then
-  echo "[-] ERROR: No project(s) indicated on the command line" >&2
-  echo "    $0 <project1> [<project2>]" >&2
-  exit 1
-fi
-
-# Check if curl is installed
-if ! command -v curl 1>/dev/null 2>&1; then
-  echo "[-] Please run: $ sudo apt install curl" >&2
-  exit 1
-fi
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-for package in ${packages}; do
-  curl \
+## Pre formatted cURL request to GitLab SaaS API
+gitlab_curl() {
+  curl 2>/dev/null \
     --silent \
     --show-error \
     --fail \
     --retry 5 \
     --header "PRIVATE-TOKEN: ${SALSA_TOKEN}" \
+    $@
+}
+
+check_return_code() {
+  code=${1:-$?}
+  if [ ${code} -eq 0 ]; then
+    echo "[+] ${project} archived ~ https://gitlab.com/${groupname}/${2:-$project}"
+  else
+    echo "[-] ERROR: Something went wrong with archival of ${2:-$project}: ${code} ~ https://gitlab.com/${groupname}/${2:-$project}" 1>&2
+  fi
+}
+
+do_archive(){
+  gitlab_curl \
     --request POST \
     --output /dev/null \
-    "https://gitlab.com/api/v4/projects/kalilinux%2Fpackages%2F${package}/archive"
+    "https://gitlab.com/api/v4/projects/${groupname//\//%2F}%2F${1:-$project}/archive"
 
-  check_return_code
+  check_return_code "$?" "${1:-$project}"
+}
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Check for API variable/file
+if [ -e "${APIFILE}" ]; then
+  echo "[i] Loading GitLab API Key (File: ${APIFILE})"
+  ## macOS doesn't like this...
+  source "${APIFILE}" \
+    || GITLAB_TOKEN=$( cat "${APIFILE}" )
+elif [ -n "${APIKEY}" ]; then
+  echo "[i] Found system variable: \$APIKEY"
+  GITLAB_TOKEN="${APIKEY}"
+fi
+## Using Debian devscript's salsa?
+if [ -n "${SALSA_TOKEN}" ]; then
+  echo "[i] Found system variable: \$SALSA_TOKEN"
+  GITLAB_TOKEN="${SALSA_TOKEN}"
+fi
+## Final check
+if [ -z "${GITLAB_TOKEN}" ]; then
+  echo "[-] ERROR: You are missing either: ${APIKEY} or a system variable: \$APIKEY" 1>&2
+  echo "    Visit: https://gitlab.com/profile/personal_access_tokens" 1>&2
+  echo "    Create a new key (which has API permission)" 1>&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > ${APIKEY}" 1>&2 # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
+  exit 1
+fi
+
+if [ -z "${packages}" ]; then
+  echo "[-] ERROR: No project(s) indicated on the command line" 1>&2
+  echo "    $0 <project1> [<project2>]" 1>&2
+  exit 1
+fi
+
+## Check for packages
+for cmd in curl; do
+  if ! command -v "${cmd}" 1>/dev/null 2>&1; then # Alt: &>/dev/null
+    echo "[-] Missing: ${cmd}"
+    #install_package ${cmd}
+    exit 1
+  fi
 done
 
-echo "[+] Done"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+for project in ${packages}; do
+  do_archive "${project}"
+done
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Done
+echo "[i] Done"
+#exit 0
diff --git a/bin/build-gitlab b/bin/build-gitlab
--- a/bin/build-gitlab
+++ b/bin/build-gitlab
@@ -13,17 +13,26 @@
 #   $ ./bin/build-gitlab project1 project2
 #
 # Requirements:
-#   # apt update && apt install --yes --no-install-recommends curl ca-certificates jq
+#   # apt-get update && apt-get install --yes --no-install-recommends curl ca-certificates jq
 #   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 ## Quit on error
 set -e
+#set -eo pipefail
 
-## echo 'APIKEY="12345678901234567890"' > .gitlab-token
-##   Developer role + allowed to merge
+## DEBUG
+#set -x
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## GitLab API Key
 ##   REF: https://gitlab.com/profile/personal_access_tokens
-apikey=".gitlab-token"
+##   Developer role + allowed to merge
+##   echo 'SALSA_TOKEN="12345678901234567890"' > ${APIFILE} # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
+APIFILE="./.gitlab-token"
 
 ## In seconds, how long to subtract from the runner max running limit
 buffer_time="480" # 480 = 8 minutes.   300 was too short when runner was 1 hour
@@ -36,62 +45,61 @@ dry=false
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
+## Pre formatted cURL request to GitLab SaaS API
 gitlab_curl() {
   curl 2>/dev/null \
-      --silent \
-      --show-error \
-      --fail \
-      --retry 5 \
-      --header "PRIVATE-TOKEN: ${APIKEY}" \
-      $@
+    --silent \
+    --show-error \
+    --fail \
+    --retry 5 \
+    --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
+    $@
 }
+
+json_output() {
+  ## --exit-status
+  jq \
+    --compact-output \
+    --monochrome-output \
+    --raw-output \
+    "$@"
+}
+
 
 ## Look for group/sub-group's ID
 ##   REF: https://docs.gitlab.com/ee/api/groups.html#search-for-group
-search_groups() {
+get_groups_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/groups/?search=${1// /%20}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[] | select (.web_url=="https://gitlab.com/groups/'"${1}"'") | .id'
+      "https://gitlab.com/api/v4/groups/?search=$( echo "${1:-$groupname}" | sed 's_ _%20_g' )" \
+    | json_output \
+        '.[] | select (.web_url=="https://gitlab.com/groups/'"$( echo "${1:-$groupname}" | sed 's_ _%20_g' )"'") | .id'
 }
 
 ## Get IDs for all (sub-)group's projects
 ##   REF: https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects
-get_groups_id() {
+get_all_groups_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/groups/${groupID}/projects/?order_by=name&sort=asc&per_page=100&page=${1}&archived=false" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[].id'
+      "https://gitlab.com/api/v4/groups/${1:-$groupid}/projects/?order_by=name&sort=asc&per_page=100&page=${2:-$page}&archived=false" \
+    | json_output \
+        '.[].id'
 }
 
 ## Get project's ID
 ##   REF: https://docs.gitlab.com/ee/api/projects.html#get-single-project
 get_projects_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${groupname//\//%2F}%2F${1}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.id'
+      "https://gitlab.com/api/v4/projects/$( echo "${1:-$groupname}" | sed 's_\/_%2F_g' )%2F${2:-$project}" \
+    | json_output \
+        '.id'
 }
 
 ## Get project's name
 ##   REF: https://docs.gitlab.com/ee/api/projects.html#get-single-project
 get_projects_name() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.name'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}" \
+    | json_output \
+        '.name'
 }
 
 ## Get all pipeline schedules
@@ -99,40 +107,35 @@ get_projects_name() {
 ##   REF: https://docs.gitlab.com/ee/api/pipeline_schedules.html
 get_projects_pipeline_schedules_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}/pipeline_schedules" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[] | select (.description=="Monthly Build") | .id'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/pipeline_schedules" \
+    | json_output \
+        '.[] | select (.description=="Monthly Build") | .id'
 }
 
 ## Run pipeline schedule
 ##   REF: https://docs.gitlab.com/ee/api/pipeline_schedules.html#run-a-scheduled-pipeline-immediately
-post_projects_pipeline_schedules_run() {
+post_projects_pipeline_schedules_run_message() {
   gitlab_curl \
       --request POST \
-      "https://gitlab.com/api/v4/projects/${1}/pipeline_schedules/${2}/play" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.message'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/pipeline_schedules/${2:-$schedules_id}/play" \
+    | json_output \
+        '.message'
 }
 
 ### Edit pipeline schedule
 ###   REF: https://docs.gitlab.com/ee/api/pipeline_schedules.html#edit-a-pipeline-schedule
-#function put_projects_pipeline_schedules_edit() {
+#put_projects_pipeline_schedules_edit_updated_at() {
 #  gitlab_curl \
 #      --request PUT \
 #      --form active="false" \
 #      "https://gitlab.com/api/v4/projects/${1}/pipeline_schedules/${2}" \
-#    | jq --compact-output --monochrome-output --raw-output '.updated_at'
+#    | json_output \
+#        '.updated_at'
 #}
 
 ### Create pipeline schedule
 ###   REF: https://docs.gitlab.com/ee/api/pipeline_schedules.html#create-a-new-pipeline-schedule
-#function post_projects_pipeline_schedules_create() {
+#post_projects_pipeline_schedules_created_at() {
 #  gitlab_curl \
 #      --request POST \
 #      --form description="Monthly Build" \
@@ -141,7 +144,8 @@ post_projects_pipeline_schedules_run() {
 #      --form cron_timezone="UTC" \
 #      --form active="false" \
 #      "https://gitlab.com/api/v4/projects/${1}/pipeline_schedules" \
-#    | jq --compact-output --monochrome-output --raw-output '.created_at'
+#    | json_output \
+#        '.created_at'
 #}
 
 ## Get all subgroups
@@ -158,7 +162,7 @@ get_subgroups_id() {
     page=$((page+1))
 
     ## Get all projects for that group's ID [page amount]
-    project=$( get_groups_id "${page}" )
+    project=$( get_all_groups_id "${1:-$groupid}" "${page}" )
 
     ## Check the response, if there isn't any more, quit
     test -z "${project}" \
@@ -185,50 +189,55 @@ packages="${packages:---all}"
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 ## Check for API variable/file
-if [ -n "${APIKEY}" ]; then
+if [ -e "${APIFILE}" ]; then
+  echo "[i] Loading GitLab API Key (File: ${APIFILE})"
+  ## macOS doesn't like this...
+  source "${APIFILE}" \
+    || GITLAB_TOKEN=$( cat "${APIFILE}" )
+elif [ -n "${APIKEY}" ]; then
   echo "[i] Found system variable: \$APIKEY"
-elif [ -e "${apikey}" ]; then
-  echo "[i] Loading GitLab API Key (File: ${apikey})"
-  source "${apikey}"
+  GITLAB_TOKEN="${APIKEY}"
 fi
 ## Using Debian devscript's salsa?
 if [ -n "${SALSA_TOKEN}" ]; then
   echo "[i] Found system variable: \$SALSA_TOKEN"
-  APIKEY="${SALSA_TOKEN}"
+  GITLAB_TOKEN="${SALSA_TOKEN}"
 fi
 ## Final check
-if [ -z "${APIKEY}" ]; then
-  echo "[-] ERROR: You are missing: $( pwd )/${apikey} or system variable: \$APIKEY" >&2
-  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
-  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/${apikey}" >&2
+if [ -z "${GITLAB_TOKEN}" ]; then
+  echo "[-] ERROR: You are missing either: ${APIKEY} or a system variable: \$APIKEY" 1>&2
+  echo "    Visit: https://gitlab.com/profile/personal_access_tokens" 1>&2
+  echo "    Create a new key (which has API permission)" 1>&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $APIKEY" 1>&2 # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
   exit 1
 fi
 
 ## Check for packages
 for cmd in jq curl; do
-  if ! command -v "${cmd}" 1>/dev/null 2>&1; then
+  if ! command -v "${cmd}" 1>/dev/null 2>&1; then # Alt: &>/dev/null
     echo "[-] Missing: ${cmd}"
+    #install_package ${cmd}
     exit 1
   fi
 done
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-groupID=$( search_groups "${groupname}" )
-if [ -z "${groupID}" ]; then
-  echo "[-] ERROR: Unable to get group ID for: https://gitlab.com/${groupname}" >&2
-  echo "    Please check your API token: $ cat $( pwd )/${apikey}" >&2
+groupid=$( get_groups_id "${groupname}" )
+if [ -z "${groupid}" ]; then
+  echo "[-] ERROR: Unable to get group ID for: https://gitlab.com/${groupname}" 1>&2
+  echo "    Please check your API token access" 1>&2
   exit 1
 fi
-echo "[i] Found (sub-)group: https://gitlab.com/${groupname} (ID: ${groupID})"
+echo "[i] Found (sub-)group: https://gitlab.com/${groupname} (ID: ${groupid})"
 
 if [ "${packages}" = "--all" ]; then
   echo "[i] Fetching all projects"
-  packages=$( get_subgroups_id "${groupID}" )
+  packages=$( get_subgroups_id "${groupid}" )
 else
   x=""
   for package in ${packages}; do
-    tmp="$( get_projects_id "${package}" )"
+    tmp="$( get_projects_id "${groupname}" "${package}" )"
     x="$( echo -e "${x}\n${tmp}" | grep -v '^$' )"
   done
   packages="${x}"
@@ -236,13 +245,13 @@ fi
 
 ## Summary is always nice
 packages_count=$( echo "${packages}" | wc -l )
-echo "[i] Found ${packages_count} projects (https://gitlab.com/${groupname})"
-
 if [ -z "${packages}" ] \
 || [ "${packages_count}" -lt 1 ]; then
   echo "[-] ERROR: Unable to get any projects" 1>&2
   exit 1
 fi
+echo "[i] Found ${packages_count} projects (https://gitlab.com/${groupname})"
+
 
 ## REF: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
 if test -z "${CI_JOB_TIMEOUT}"; then
@@ -255,26 +264,26 @@ fi
 
 ## For every project
 i=0
-for id in ${packages}; do
+for projectid in ${packages}; do
   i=$((i+1))
-  name=$( get_projects_name "${id}" )
+  name=$( get_projects_name "${projectid}" )
 
-  schedules_id=$( get_projects_pipeline_schedules_id "${id}" )
+  schedules_id=$( get_projects_pipeline_schedules_id "${projectid}" )
 
   test -z "${schedules_id}" \
-    && echo "[-] Missing 'Monthly Build' for ${name} (ID: ${id}) ~ https://gitlab.com/${groupname}/${name}/-/pipeline_schedules" 1>&2 \
+    && echo "[-] Missing 'Monthly Build' for ${name} (ID: ${projectid}) ~ https://gitlab.com/${groupname}/${name}/-/pipeline_schedules" 1>&2 \
     && continue
-#        && message=$( post_projects_pipeline_schedules_create "${id}" ) \
+#        && message=$( post_projects_pipeline_schedules_created_at "${projectid}" ) \
 
-#      echo "[+] (${i}/${packages_count}) Editing 'Monthly Build' for ${name} (ID: ${id})"
-#      message=$( put_projects_pipeline_schedules_edit "${id}" "${schedules_id}" )
-#      #echo "[i]   ${name} (ID: ${id}): ${message}"
+#      echo "[+] (${i}/${packages_count}) Editing 'Monthly Build' for ${name} (ID: ${projectid})"
+#      message=$( put_projects_pipeline_schedules_edit_updated_at "${projectid}" "${schedules_id}" )
+#      #echo "[i]   ${name} (ID: ${projectid}): ${message}"
 
-  echo "[+] (${i}/${packages_count}) Running 'Monthly Build' for ${name} (ID: ${id})"
+  echo "[+] (${i}/${packages_count}) Running 'Monthly Build' for ${name} (ID: ${projectid})"
   if [ "${dry}" != "true" ]; then
-    message=$( post_projects_pipeline_schedules_run "${id}" "${schedules_id}" )
+    message=$( post_projects_pipeline_schedules_run_message "${projectid}" "${schedules_id}" )
     if [ "${message}" != "201 Created" ]; then
-      echo "[-]   Unexpected response for ${name} (ID: ${id}): ${message}" 1>&2
+      echo "[-]   Unexpected response for ${name} (ID: ${projectid}): ${message}" 1>&2
     fi
   fi
 
@@ -286,4 +295,8 @@ for id in ${packages}; do
   fi
 done
 
-echo "[+] Done"
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Done
+echo "[i] Done"
+#exit 0
diff --git a/bin/retry-gitlab b/bin/retry-gitlab
--- a/bin/retry-gitlab
+++ b/bin/retry-gitlab
@@ -13,17 +13,26 @@
 #   $ ./bin/retry-gitlab project1 project2
 #
 # Requirements:
-#   # apt update && apt install --yes --no-install-recommends curl ca-certificates jq
+#   # apt-get update && apt-get install --yes --no-install-recommends curl ca-certificates jq
 #   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
 ## Quit on error
 set -e
+#set -eo pipefail
 
-## echo 'APIKEY="12345678901234567890"' > .gitlab-token
-##   Developer role + allowed to merge
+## DEBUG
+#set -x
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## GitLab API Key
 ##   REF: https://gitlab.com/profile/personal_access_tokens
-apikey=".gitlab-token"
+##   Developer role + allowed to merge
+##   echo 'SALSA_TOKEN="12345678901234567890"' > ${APIFILE} # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
+APIFILE="./.gitlab-token"
 
 ## What (sub-)group to search
 groupname="kalilinux/packages"
@@ -34,74 +43,69 @@ quiet=false
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
+## Pre formatted cURL request to GitLab SaaS API
 gitlab_curl() {
   curl 2>/dev/null \
-      --silent \
-      --show-error \
-      --fail \
-      --retry 5 \
-      --header "PRIVATE-TOKEN: ${APIKEY}" \
-      $@
+    --silent \
+    --show-error \
+    --fail \
+    --retry 5 \
+    --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" \
+    $@
+}
+
+json_output() {
+  ## --exit-status
+  jq \
+    --compact-output \
+    --monochrome-output \
+    --raw-output \
+    "$@"
 }
 
 ## Look for group/sub-group's ID
 ##   REF: https://docs.gitlab.com/ee/api/groups.html#search-for-group
-search_groups() {
+get_groups_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/groups/?search=${1// /%20}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[] | select (.web_url=="https://gitlab.com/groups/'"${1}"'") | .id'
+      "https://gitlab.com/api/v4/groups/?search=$( echo "${1:-$groupname}" | sed 's_ _%20_g' )" \
+    | json_output \
+        '.[] | select (.web_url=="https://gitlab.com/groups/'"${1:-$groupname}"'") | .id'
 }
 
 ## Get IDs for all (sub-)group's projects
 ##   REF: https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects
-get_groups_id() {
+get_all_groups_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/groups/${groupID}/projects/?order_by=name&sort=asc&per_page=100&page=${1}&archived=false" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[].id'
+      "https://gitlab.com/api/v4/groups/${1:-$groupid}/projects/?order_by=name&sort=asc&per_page=100&page=${2:-$page}&archived=false" \
+    | json_output \
+        '.[].id'
 }
 
 ## Get project's ID
 ##   REF: https://docs.gitlab.com/ee/api/projects.html#get-single-project
 get_projects_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${groupname//\//%2F}%2F${1}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.id'
+      "https://gitlab.com/api/v4/projects/$( echo "${1:-$groupname}" | sed 's_\/_%2F_g' )%2F${2:-$project}" \
+    | json_output \
+        '.id'
 }
 
 ## Get project's name
 ##   REF: https://docs.gitlab.com/ee/api/projects.html#get-single-project
 get_projects_name() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.name'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}" \
+    | json_output \
+        '.name'
 }
 
 ## Get pipeline latest status
 ##   REF: https://docs.gitlab.com/ee/api/pipelines.html#get-the-latest-pipeline
 get_projects_pipelines_latest_status_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}/pipelines/latest" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.status, .id'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/pipelines/latest" \
+    | json_output \
+        '.status, .id'
 }
 
 ## Get pipeline job status
@@ -109,24 +113,18 @@ get_projects_pipelines_latest_status_id() {
 ##   created, pending, running, failed, success, canceled, skipped, waiting_for_resource, manual
 get_projects_pipelines_jobs_id() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}/pipelines/${2}/jobs?scope[]=failed&scope[]=canceled&scope[]=skipped&scope[]=waiting_for_resource&include_retried=false" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.[].id'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/pipelines/${2:-$piplineid}/jobs?scope[]=failed&scope[]=canceled&scope[]=skipped&scope[]=waiting_for_resource&include_retried=false" \
+    | json_output \
+        '.[].id'
 }
 
 ## Get job name
 ##   REF: https://docs.gitlab.com/ee/api/jobs.html#get-a-single-job
 get_projects_job_name() {
   gitlab_curl \
-      "https://gitlab.com/api/v4/projects/${1}/jobs/${2}" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.name'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/jobs/${2:-$jobid}" \
+    | json_output \
+        '.name'
 }
 
 ## Retry complete pipeline
@@ -134,21 +132,19 @@ get_projects_job_name() {
 post_projects_job_retry_id() {
   gitlab_curl \
       --request POST \
-      "https://gitlab.com/api/v4/projects/${1}/jobs/${2}/retry" \
-    | jq \
-      --compact-output \
-      --monochrome-output \
-      --raw-output \
-      '.id'
+      "https://gitlab.com/api/v4/projects/${1:-$projectid}/jobs/${2:-$jobid}/retry" \
+    | json_output \
+        '.id'
 }
 
 ### Retry complete pipeline
 ###   REF: https://docs.gitlab.com/ee/api/pipeline_schedules.html#run-a-scheduled-pipeline-immediately
-#function post_projects_pipeline_retry_id() {
+#post_projects_pipeline_retry_id() {
 #  gitlab_curl \
 #      --request POST \
-#      "https://gitlab.com/api/v4/projects/${1}/pipelines/${2}/retry" \
-#    | jq --compact-output --monochrome-output --raw-output '.id'
+#      "https://gitlab.com/api/v4/projects/${1:-$projectid}/pipelines/${2:-$pipeline_id}/retry" \
+#    | json_output \
+#        '.id'
 #}
 
 ## Get all subgroups
@@ -165,7 +161,7 @@ get_subgroups_id() {
     page=$((page+1))
 
     ## Get all projects for that group's ID [page amount]
-    project=$( get_groups_id "${page}" )
+    project=$( get_all_groups_id "${groupid}" "${page}" )
 
     ## Check the response, if there isn't any more, quit
     test -z "${project}" \
@@ -175,6 +171,41 @@ get_subgroups_id() {
   done
   echo "${projects}"
 }
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Check for API variable/file
+if [ -e "${APIFILE}" ]; then
+  echo "[i] Loading GitLab API Key (File: ${APIFILE})"
+  ## macOS doesn't like this...
+  source "${APIFILE}" \
+    || GITLAB_TOKEN=$( cat "${APIFILE}" )
+elif [ -n "${APIKEY}" ]; then
+  echo "[i] Found system variable: \$APIKEY"
+  GITLAB_TOKEN="${APIKEY}"
+fi
+## Using Debian devscript's salsa?
+if [ -n "${SALSA_TOKEN}" ]; then
+  echo "[i] Found system variable: \$SALSA_TOKEN"
+  GITLAB_TOKEN="${SALSA_TOKEN}"
+fi
+## Final check
+if [ -z "${GITLAB_TOKEN}" ]; then
+  echo "[-] ERROR: You are missing either: ${APIKEY} or a system variable: \$APIKEY" 1>&2
+  echo "    Visit: https://gitlab.com/profile/personal_access_tokens" 1>&2
+  echo "    Create a new key (which has API permission)" 1>&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $APIKEY" 1>&2 # SALSA_TOKEN is due to Debian's devscripts's salsa.pl
+  exit 1
+fi
+
+## Check for packages
+for cmd in jq curl; do
+  if ! command -v "${cmd}" 1>/dev/null 2>&1; then # Alt: &>/dev/null
+    echo "[-] Missing: ${cmd}"
+    #install_package ${cmd}
+    exit 1
+  fi
+done
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
@@ -192,51 +223,21 @@ packages="${packages:---all}"
 
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-## Check for API variable/file
-if [ -n "${APIKEY}" ]; then
-  echo "[i] Found system variable: \$APIKEY"
-elif [ -e "${apikey}" ]; then
-  echo "[i] Loading GitLab API Key (File: ${apikey})"
-  source "${apikey}"
-fi
-## Using Debian devscript's salsa?
-if [ -n "${SALSA_TOKEN}" ]; then
-  echo "[i] Found system variable: \$SALSA_TOKEN"
-  APIKEY="${SALSA_TOKEN}"
-fi
-## Final check
-if [ -z "${APIKEY}" ]; then
-  echo "[-] ERROR: You are missing: $( pwd )/${apikey} or system variable: \$APIKEY" >&2
-  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
-  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/${apikey}" >&2
+groupid=$( get_groups_id "${groupname}" )
+if [ -z "${groupid}" ]; then
+  echo "[-] ERROR: Unable to get group ID for: https://gitlab.com/${groupname}" 1>&2
+  echo "    Please check your API token access" 1>&2
   exit 1
 fi
-
-## Check for packages
-for cmd in jq curl; do
-  if ! command -v "${cmd}" 1>/dev/null 2>&1; then
-    echo "[-] Missing: ${cmd}"
-    exit 1
-  fi
-done
-
-# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-
-groupID=$( search_groups "${groupname}" )
-if [ -z "${groupID}" ]; then
-  echo "[-] ERROR: Unable to get group ID for: https://gitlab.com/${groupname}" >&2
-  echo "    Please check your API token: $ cat $( pwd )/${apikey}" >&2
-  exit 1
-fi
-echo "[i] Found (sub-)group: https://gitlab.com/${groupname} (ID: ${groupID})"
+echo "[i] Found (sub-)group: https://gitlab.com/${groupname} (ID: ${groupid})"
 
 if [ "${packages}" = "--all" ]; then
   echo "[i] Fetching all projects"
-  packages=$( get_subgroups_id "${groupID}" )
+  packages=$( get_subgroups_id "${groupid}" )
 else
   x=""
-  for package in ${packages}; do
-    tmp="$( get_projects_id "${package}" )"
+  for project in ${packages}; do
+    tmp="$( get_projects_id "${groupname}" "${project}" )"
     x="$( echo -e "${x}\n${tmp}" | grep -v '^$' )"
   done
   packages="${x}"
@@ -248,12 +249,12 @@ echo "[i] Found ${packages_count} projects (https://gitlab.com/${groupname})"
 ## For every project
 i=0
 y=0
-for id in ${packages}; do
-  name=$( get_projects_name "${id}" )
+for projectid in ${packages}; do
+  name=$( get_projects_name "${projectid}" )
 
-  pipline_latest=$( get_projects_pipelines_latest_status_id "${id}" )
+  pipline_latest=$( get_projects_pipelines_latest_status_id "${projectid}" )
   pipline_status=$( echo "${pipline_latest}" | head -n 1 )
-  pipline_id=$( echo "${pipline_latest}" | tail -n 1 )
+  piplineid=$( echo "${pipline_latest}" | tail -n 1 )
 
   test -z "${pipline_status}" \
     && pipline_status="disabled"
@@ -265,28 +266,28 @@ for id in ${packages}; do
   [ "${pipline_status}" = "canceled" ]; then
   #[ "${pipline_status}" = "disabled" ] ||
     ## Retry ALL of the pipeline
-    #id=$( post_projects_pipeline_retry_id "${id}" "${pipline_id}" )
+    #id=$( post_projects_pipeline_retry_id "${projectid}" "${piplineid}" )
 
     ## Get failed jobs
-    jobs_id=$( get_projects_pipelines_jobs_id "${id}" "${pipline_id}" )
+    jobsid=$( get_projects_pipelines_jobs_id "${projectid}" "${piplineid}" )
 
     ## Re-run each failed job
-    for job_id in ${jobs_id}; do
+    for jobid in ${jobsid}; do
       ## This isn't the most efficient way of doing it. Quick & dirty
-      job_name=$( get_projects_job_name "${id}" "${job_id}" )
+      job_name=$( get_projects_job_name "${projectid}" "${jobid}" )
 
       ## If we don't get the job name for any reason, skip
       if [ -z "${job_name}" ]; then
         if [ "${quiet}" != "true" ]; then
-          echo "[-] Could not get ${pipline_status} job name for ${name} ~ https://gitlab.com/${groupname}/${name}/-/jobs/${job_id}" >&2
-          echo "                                                           https://gitlab.com/${groupname}/${name}/-/pipelines/${pipline_id}" >&2
+          echo "[-] Could not get ${pipline_status} job name for ${name} ~ https://gitlab.com/${groupname}/${name}/-/jobs/${jobid}" 1>&2
+          echo "                                                           https://gitlab.com/${groupname}/${name}/-/pipelines/${piplineid}" 1>&2
         fi
         continue
       fi
 
-      echo "[i] Re-running ${name} (${id})'s ${pipline_status} job: ${job_name} ~ https://gitlab.com/${groupname}/${name}/-/jobs/${job_id}"
+      echo "[i] Re-running ${name} (${projectid})'s ${pipline_status} job: ${job_name} ~ https://gitlab.com/${groupname}/${name}/-/jobs/${jobid}"
       if [ "${dry}" != "true" ]; then
-        project_id=$( post_projects_job_retry_id "${id}" "${job_id}" )
+        project_id=$( post_projects_job_retry_id "${projectid}" "${jobid}" )
       elif [ "${quiet}" != "true" ]; then
         echo "[i]  DRY RUN"
       fi
@@ -298,4 +299,10 @@ for id in ${packages}; do
 done
 
 echo "[+] Re-ran ${y} unsuccessful jobs (${i} broken pipelines)"
-echo "[+] Done"
+
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Done
+echo "[i] Done"
+#exit 0
