Restructure

diff --git a/bin/archive-gitlab b/bin/archive-gitlab
--- a/bin/archive-gitlab
+++ b/bin/archive-gitlab
@@ -1,41 +1,73 @@
 #!/usr/bin/env bash
 #
-# Archived a single package (remote repository on GitLab.com)
+# Archived project(s) (aka package repositories) on GitLab.com
+#   _Open MR one day for devscripts salsa_
 #
-# Usage: ./bin/archive-package [<packages>]
+# Usage: $ ./bin/archive-gitlab <project1> [<project2>]
+#
+# Example:
+#   $ ./bin/archive-gitlab project1 project2
+#   $ SALSA_TOKEN=xxx ./bin/archive-gitlab project
+#
+# Requirements:
+#   # apt update && apt install --yes --no-install-recommends curl ca-certificates
+#   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
+## Quit on error
 set -e
 
-package=$1
-source .gitlab-token
+packages=$*
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 check_return_code() {
-  if [ $? -eq 0 ]; then
-    echo "Project kalilinux/packages/${package} archived"
+  code=$?
+  if [ ${code} -eq 0 ]; then
+    echo "[+] ${package} archived ~ https://gitlab.com/kalilinux/packages/${package}"
   else
-    echo "[-] ERROR: Something went wrong with archival of https://gitlab.com/kalilinux/packages/${package}" >&2
-    exit 1
+    echo "[-] ERROR: Something went wrong with archival of ${package}: ${code} ~ https://gitlab.com/kalilinux/packages/${package}" >&2
   fi
 }
 
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+source .gitlab-token 2>/dev/null \
+  || true
+
 if [ -z "${SALSA_TOKEN}" ]; then
-  echo "[-] ERROR: No token configured in $( pwd )/.gitlab-token" >&2
+  echo "[-] ERROR: You are missing: $( pwd )/.gitlab-token" >&2
+  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/.gitlab-token" >&2
   exit 1
 fi
 
-if [ -z "${package}" ]; then
-  echo "[-] ERROR: No package indicated on the command line" >&2
-  echo "[-] $0 <package>" >&2
+if [ -z "${packages}" ]; then
+  echo "[-] ERROR: No project(s) indicated on the command line" >&2
+  echo "    $0 <project1> [<project2>]" >&2
   exit 1
 fi
 
-curl \
-  --silent \
-  --show-error \
-  --request POST \
-  --header "PRIVATE-TOKEN: ${SALSA_TOKEN}" \
-  --output /dev/null \
-  "https://gitlab.com/api/v4/projects/kalilinux%2Fpackages%2F${package}/archive"
+# Check if curl is installed
+if ! command -v curl 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install curl" >&2
+  exit 1
+fi
 
-check_return_code
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+for package in ${packages}; do
+  curl \
+    --silent \
+    --show-error \
+    --fail \
+    --retry 5 \
+    --header "PRIVATE-TOKEN: ${SALSA_TOKEN}" \
+    --request POST \
+    --output /dev/null \
+    "https://gitlab.com/api/v4/projects/kalilinux%2Fpackages%2F${package}/archive"
+
+  check_return_code
+done
+
+echo "[+] Done"
diff --git a/bin/archive-local b/bin/archive-local
--- a/bin/archive-local
+++ b/bin/archive-local
@@ -1,67 +1,76 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
-# Move any locally clone repositories which have been remotely archived
+# Move any locally clone project(s) (aka package repositories) which have been remotely archived on GitLab.com
 #
-# Usage: ./bin/archive-team-repo [<packages-path>] [<archived-path>]
-# Without argument, will default to:
-#   - packages-path: ./../
-#   - archived-path: ./../archived/
+# Usage: $ ./bin/archive-local [<project-path>] [<archived-path>]
+#   Without argument, will default to:
+#     - project-path: ./../packages/
+#     - archived-path: ./../archived/
+#
+# Example:
+#   $ ./bin/archive-local
+#   $ ./bin/archive-local ~/kali/packages ~/kali/packages/archived
+#
+# Requirements:
+#   $ ./bin/clone-gitlab
 #
 
+## Quit on error
 set -e
 
-# Base folder, to locate mrconfig
-repo_dir=$( dirname $0 )/..
-# Where the checkout packages are
-package_dir=$1
-# Where to move archived packages to
-archive_dir=$2
+## Base folder, to locate mrconfig
+repo_dir=$( dirname "$0" )/..
 
-# Check before doing action
+## Where the clone projects are
+package_dir="${1:-$repo_dir/../packages}"
+
+## Where to move archived projects to
+archive_dir="${2:-$repo_dir/../archived}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Check before doing action
 confirm_to_continue() {
-  read -p "[?] Shall I proceed? [Y/n] " reply
+  read -p "[?] Proceed? [Y/n] " reply
   case "${reply}" in
-  [Yy]|"")
-    ;;
-  *)
-    echo "[-] Cancelling operation" >&2
-    exit 0
-    ;;
+    [Yy]|"")
+      ;;
+    *)
+      echo "[-] Cancelling operation" >&2
+      exit 0
+      ;;
   esac
 }
 
-# No arguments, use default location
-if [ -z "${package_dir}" ]; then
-  package_dir=$( realpath ${repo_dir}/.. )
-fi
-package_dir=$( realpath ${package_dir} )
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-# No arguments, use default location
-if [ -z "${archive_dir}" ]; then
-  archive_dir=$( realpath ${repo_dir}/../archived )
-fi
-archive_dir=$( realpath ${archive_dir} )
+## Find absolute path
+package_dir=$( realpath -m "${package_dir}" )
+archive_dir=$( realpath -m "${archive_dir}" )
 
-# Create archive location
-mkdir -pv "${archive_dir}/"
-
-# Copy myrepos config
+## Check for myrepos config
 if [ ! -e "${package_dir}/.mrconfig" ]; then
-  echo "[-] Unable to locate '${package_dir}/.mrconfig'" >&2
-  echo "[-] Please run './bin/setup-team-repos ${package_dir}'" >&2
+  echo "[-] Unable to locate: ${package_dir}/.mrconfig" >&2
+  echo "    Please run: $ ./bin/clone-gitlab ${package_dir}" >&2
   exit 1
 fi
 
-# Feedback about action
-echo "[>] I will compare '${package_dir}/.mrconfig' to '${package_dir}' to see any packages which have been archived"
-confirm_to_continue
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
-# Not using while loop, due to nested read
-# Spaces in path name will break loop (should not have any tho)
-for package in $(ls -1 "${package_dir}/"); do
+## Create archive location
+mkdir -pv "${archive_dir}/"
+
+## Feedback about action
+echo "[>] Comparing '${package_dir}/.mrconfig' with 'ls ${package_dir}/*' to see if any projects which may have been archived"
+
+## Not using while loop, due to nested read
+## Spaces in path name will break loop (should not have any though)
+for package in $( ls -1 "${package_dir}/" ); do
   if ! grep -q "^\[${package}\]$" "${package_dir}/.mrconfig"; then
-    echo "[>] Move '${package_dir}/${package}' to '${archive_dir}/${package}'?"
+    echo "[>] Archive '${package_dir}/${package}' to '${archive_dir}/${package}'"
     confirm_to_continue
     mv -v "${package_dir}/${package}" "${archive_dir}/${package}"
   fi
 done
+
+echo "[+] Done"
diff --git a/bin/clone-gitlab b/bin/clone-gitlab
--- a/bin/clone-gitlab
+++ b/bin/clone-gitlab
@@ -1,63 +1,113 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
-# Download every repo
+# Clone & update every project(s) (aka package repositories) on GitLab.com
 #
-# Usage: ./bin/setup-team-repo [<packages-path>]
-# Without argument, will default to parent folder ("./../")
+# Usage: $ ./bin/clone-gitlab [<project-path>]
+#   Without argument, will default to:
+#     - project-path: ./../packages/
+#
+# Example:
+#   $ ./bin/clone-gitlab
+#   $ ./bin/clone-gitlab ~/kali/packages
+#
+# Requirements:
+#   - SSH key added to GitLab.com ~ https://gitlab.com/-/profile/keys
+#   # apt update && apt install --yes --no-install-recommends mr git-buildpackage openssh-client
+#   - Debian 12 or higher
 #
 
+## Quit on error
 set -e
 
-# Base folder, to locate mrconfig
-repo_dir=$( dirname $0 )/..
-# Where to checkout all packages
-target_dir=$1
+## Base folder, to locate mrconfig
+repo_dir=$( dirname "$0" )/..
 
-# Check before doing action
+## Where to clone projects
+package_dir="${1:-$repo_dir/../packages}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Check before doing action
 confirm_to_continue() {
-  read -p "[?] Shall I proceed? [Y/n] " reply
+  read -p "[?] Proceed? [Y/n] " reply
   case "${reply}" in
-  [Yy]|"")
-    ;;
-  *)
-    echo "[-] Cancelling operation" >&2
-    exit 0
-    ;;
+    [Yy]|"");;
+    *)
+      echo "[-] Cancelling operation" >&2
+      exit 0
+      ;;
   esac
 }
 
-# Check myrepos is installed
-if ! dpkg -s mr >/dev/null 2>/dev/null && ! dpkg -s myrepos >/dev/null 2>/dev/null; then
-  echo "[-] Please 'sudo apt install mr' before running $0" >&2
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Find absolute path
+package_dir=$( realpath -m "${package_dir}" )
+repo_dir=$( realpath -m "${repo_dir}" )
+
+## Check for required packages/command - mr
+if ! command -v mr 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install mr" >&2
+  exit 1
+fi
+## Check for required packages/command - gbp
+if ! command -v gbp 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install git-buildpackage" >&2
+  exit 1
+fi
+## Check for required packages/command - git via ssh
+if ! command -v ssh 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install openssh-client" >&2
   exit 1
 fi
 
-# No arguments, use default location of ../
-if [ -z "${target_dir}" ]; then
-  target_dir=$( realpath ${repo_dir}/.. )
-fi
-target_dir=$( realpath ${target_dir} )
-
-# Create checkout location
-mkdir -p "${target_dir}/"
-
-# Feedback about action
-echo "[>] I will setup '${target_dir}/.mrconfig' to easily checkout all repositories"
-confirm_to_continue
-
-# Copy myrepos config
-cp "${repo_dir}/mrconfig" "${target_dir}/.mrconfig"
-if [ ! -e ~/.mrtrust ] || ! grep -q "${target_dir}/.mrconfig" ~/.mrtrust; then
-  echo "${target_dir}/.mrconfig" >>~/.mrtrust
+## Check for myrepos config
+if [ ! -e "${repo_dir}/mrconfig" ]; then
+  echo "[-] Unable to locate: ${repo_dir}/mrconfig" >&2
+  echo "    Please run: $ ./bin/update-mrconfig" >&2
+  exit 1
 fi
 
-# Feedback about action
-echo "[>] I will run 'mr --force checkout' to clone all repositories (in ${target_dir})"
+## Check for ~/.ssh folder
+if [ ! -d "${HOME}/.ssh" ]; then
+  echo "[i] Missing: ${HOME}/.ssh"
+  mkdir -p "${HOME}/.ssh"
+  chmod 0700 "${HOME}/.ssh"
+fi
+
+if ssh -o StrictHostKeyChecking=yes gitlab.com 2>&1 | grep -q 'host key is known'; then
+  echo "[i] Missing: gitlab.com in ~/.ssh/known_hosts"
+  ssh-keyscan -H -t rsa gitlab.com 2>/dev/null >> ~/.ssh/known_hosts
+fi
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Create clone location
+mkdir -pv "${package_dir}/"
+
+## Feedback about action
+echo "[>] To easily clone all repositories, create: ${package_dir}/.mrconfig"
 confirm_to_continue
 
-# Clone repos
-cd "${target_dir}/"
-mr --force \
-   --verbose \
-   --stats \
-   checkout
+## Copy myrepos config
+cp -v "${repo_dir}/mrconfig" "${package_dir}/.mrconfig"
+
+## Set trust
+if [ ! -e ~/.mrtrust ] || ! grep -q "${package_dir}/.mrconfig" ~/.mrtrust; then
+  echo "${package_dir}/.mrconfig" >>~/.mrtrust
+fi
+
+## Feedback about action
+echo "[>] Force clone all repositories into: ${package_dir}"
+confirm_to_continue
+
+## Clone projects
+mr \
+  --force \
+  --stats \
+  --directory "${package_dir}/" \
+  --config "${package_dir}/.mrconfig" \
+  update  # checkout = just clone without updating
+  #--verbose # Feels little too noisy
+
+echo "[+] Done"
diff --git a/bin/configure-gitlab b/bin/configure-gitlab
--- a/bin/configure-gitlab
+++ b/bin/configure-gitlab
@@ -1,43 +1,80 @@
 #!/usr/bin/env bash
 #
-# Usage: ./bin/configure-packages <packages>
-# If no arguments, will do '--all'
+# Configure any remote project(s) (aka package repositories) which are on GitLab.com
+#   This will apply our "template"
+#
+# Usage: $ ./bin/configure-gitlab [--all|<project1>] [<project2>]
+#   Without argument, will default to: '--all'
+#
+# Example:
+#   $ ./bin/configure-gitlab
+#   $ ./bin/configure-gitlab --all
+#   $ ./bin/configure-gitlab project1 project2
+#   $ yes | ./bin/configure-gitlab project
+#
+# Requirements:
+#   # apt update && apt install --yes --no-install-recommends devscripts libgitlab-api-v4-perl
+#   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
-package="${1:---all}"
-source .gitlab-token
+## Quit on error
+set -e
 
-if [ ! -e ./salsa/auth.conf ] || [ ! -e ./salsa/packages.conf ]; then
-  echo "ERROR: You don't seem to be in the correct directory" >&2
-  echo "Run this tool from the top-level directory as: ./bin/configure-packages" >&2
-  exit 1
-fi
+packages="${*:---all}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+source .gitlab-token 2>/dev/null \
+  || true
 
 if [ -z "${SALSA_TOKEN}" ]; then
-  echo "ERROR: You are missing ./.gitlab-token" >&2
-  echo "Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
-  echo "Afterwards: echo \"SALSA_TOKEN='XXX'\" > ./.gitlab-token" >&2
+  echo "[-] ERROR: You are missing: $( pwd )/.gitlab-token" >&2
+  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/.gitlab-token" >&2
   exit 1
 fi
 
-if [ "${package}" = "--all" ]; then
-  # This is done, as --all would be doing BOTH --archived and --no-archived
-  # 5034987 = https://gitlab.com/kalilinux/packages
-  echo "[i] No selected Package. Doing --all. Fetching packages list..."
-  package=$(salsa --conf-file ./salsa/auth.conf \
-        --group-id 5034987 \
-        --no-archived \
-        ls \
-    | awk '/Name:/ { print $2 }' \
-    | sort)
-
-  echo "[i] Total: $(echo "${package}" | wc -l) packages"
+if [ ! -e ./salsa.d/auth.conf ] \
+|| [ ! -e ./salsa.d/packages.conf ]; then
+  echo "[-] ERROR: You don't seem to be in the correct directory" >&2
+  echo "    Run this tool from the top-level directory as: ./bin/configure-gitlab" >&2
+  exit 1
 fi
 
+# Check if salsa is installed
+if ! command -v salsa 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install devscripts" >&2
+  exit 1
+fi
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+if [ "${packages}" = "--all" ]; then
+  ## group-id 5034987 = https://gitlab.com/kalilinux/packages
+  ## ls has changed its default behaviour before, to include "archived" & "non-archived" repos
+  ## Removing WIP as its Kali's way of tracking packages which are Work In Progress queue
+  echo "[i] Fetching all projects"
+  packages=$( salsa \
+                   --conf-file ./salsa.d/auth.conf \
+                   --group-id 5034987 \
+                   --no-archived \
+                   ls \
+              | awk '/Name:/ {print $2}' \
+              | grep -v "^WIP$" \
+              | sort )
+
+  ## Summary is always nice
+  echo "[i] Total: $( echo "${packages}" | wc -l ) projects"
+fi
+
+## Update projects
 salsa \
-  --conf-file ./salsa/auth.conf \
-  --conf-file +./salsa/packages.conf \
+  --conf-file  ./salsa.d/auth.conf \
+  --conf-file +./salsa.d/packages.conf \
   --debug \
   --verbose \
   --no-fail \
-  update_safe ${package}
+  update_safe \
+  ${packages}
+
+echo "[+] Done"
diff --git a/bin/unprotect-gitlab b/bin/unprotect-gitlab
--- a/bin/unprotect-gitlab
+++ b/bin/unprotect-gitlab
@@ -1,23 +1,86 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
-# Will reset branch protection to allow developers to push and merge
+# Will (re)set branch protection to allow developers to push and merge on GitLab.com
 #
-# Usage: ./bin/unprotect [<package> ...]
-# Without argument, will default to everything in https://gitlab.com/kalilinux/packages/
+# Usage: $ ./bin/unprotect-gitlab [--all|<project1>] [<project2>]
+#   Without argument, will default to: '--all'
+#
+# Example:
+#   $ ./bin/unprotect-gitlab
+#   $ ./bin/unprotect-gitlab --all
+#   $ ./bin/unprotect-gitlab project1 project2
+#
+# Requirements:
+#   # apt update && apt install --yes --no-install-recommends devscripts libgitlab-api-v4-perl
+#   - GitLab API token: https://gitlab.com/-/profile/personal_access_tokens
 #
 
+## Quit on error
 set -e
 
-if [ -n "$1" ]; then
-  projects="$@"
-else
-  ## 5034987 = https://gitlab.com/kalilinux/packages
-  projects=$(salsa --conf-file ./salsa/auth.conf --group-id 5034987 ls | awk '/Name:/ {print $2}' | sort)
+branch="kali/master"
+packages="${*:---all}"
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+source .gitlab-token 2>/dev/null \
+  || true
+
+if [ -z "${SALSA_TOKEN}" ]; then
+  echo "[-] ERROR: You are missing: $( pwd )/.gitlab-token" >&2
+  echo "    Create: https://gitlab.com/-/profile/personal_access_tokens" >&2
+  echo "    Afterwards: echo \"SALSA_TOKEN='XXX'\" > $( pwd )/.gitlab-token" >&2
+  exit 1
 fi
 
-for project in ${projects}; do
-  echo "Setting branch protection for https://gitlab.com/kalilinux/packages/${project}"
-  salsa --conf-file ./salsa/auth.conf --verbose --group-id 5034987 protect_branch ${project} kali/master no
-  salsa --conf-file ./salsa/auth.conf --verbose --group-id 5034987 protect_branch ${project} kali/master d d
+if [ ! -e ./salsa.d/auth.conf ]; then
+  echo "[-] ERROR: You don't seem to be in the correct directory" >&2
+  echo "    Run this tool from the top-level directory as: ./bin/unprotect-gitlab" >&2
+  exit 1
+fi
+
+# Check if salsa is installed
+if ! command -v salsa 1>/dev/null 2>&1; then
+  echo "[-] Please run: $ sudo apt install devscripts" >&2
+  exit 1
+fi
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+if [ "${packages}" = "--all" ]; then
+  ## group-id 5034987 = https://gitlab.com/kalilinux/packages
+  ## ls has changed its default behaviour before, to include "archived" & "non-archived" repos
+  ## Removing WIP as its Kali's way of tracking packages which are Work In Progress queue
+  echo "[i] Fetching all projects"
+  packages=$( salsa \
+                   --conf-file ./salsa.d/auth.conf \
+                   --group-id 5034987 \
+                   --no-archived \
+                   ls \
+              | awk '/Name:/ {print $2}' \
+              | grep -v "^WIP$" \
+              | sort )
+
+  ## Summary is always nice
+  echo "[i] Total: $( echo "${packages}" | wc -l ) projects"
+fi
+
+for package in ${packages}; do
+  echo "[>] Setting branch protection for ${package} ~ https://gitlab.com/kalilinux/packages/${package}"
+
+  ## no  = Unprotect
+  ## d d = Protect (merge and push for developers)
+  ## group-id 5034987 = https://gitlab.com/kalilinux/packages
+  for action in "no" "d d"; do
+    salsa \
+      --conf-file ./salsa.d/auth.conf \
+      --verbose \
+      --group-id 5034987 \
+      protect_branch \
+      ${package} \
+      "${branch}" ${action}
+  done
   echo ""
 done
+
+echo "[+] Done"
diff --git a/bin/update-mrconfig b/bin/update-mrconfig
--- a/bin/update-mrconfig
+++ b/bin/update-mrconfig
@@ -1,55 +1,187 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 #
-# Refresh mrconfig with active repos
-# After running, may wish to execute:
-#   - $ ./bin/setup-team-repo   (Pull any new repos)
-#   - $ ./bin/archive-team-repo (Move any old repos)
-#   - $ ./bin/auto-update       (Configure repos)
+# Recreate mrconfig with active project(s) (aka package repositories) which are on GitLab.com
+#   This was more 'simpler' at one stage, as it used Debia devscript's salsa (see git history)
+#   However:
+#     - Its a much larger package (which slows down GitLab's CI)
+#     - (At the time of writing) it wasn't retrying on failure
+#       libgitlab-api-v4-perl has 'retries' but not being used
+#        _Open MR one day for devscripts salsa to add support_
+#
+# Usage: $ ./bin/update-mrconfig [--https|--ssh]
+#   Without argument, will default to: '--ssh'
+#
+# Example:
+#   $ ./bin/update-mrconfig
+#   $ ./bin/update-mrconfig --https
+#   $ ./bin/update-mrconfig --ssh
+#
+# Requirements:
+#   # apt update && apt install --yes --no-install-recommends curl ca-certificates jq
+#
 
-#
-# Usage: ./bin/update-mrconfig
-# There are no arguments
-#
-
+## Quit on error
 set -e
 
 export LC_ALL=C
 
-## 5034987 = https://gitlab.com/kalilinux/packages
-projects=$(salsa --conf-file ./salsa/auth.conf --group-id 5034987 ls | awk '/Name:/ {print $2}' | sort)
+auth="${1:-ssh}"
+branch="kali/master"
+groupname="kalilinux/packages"
 
-if [ -z "${projects}" ]; then
-  echo "[-] Unable to get any repos" 1>&2
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+gitlab_curl() {
+  curl 2>/dev/null \
+      --silent \
+      --show-error \
+      --fail \
+      --retry 5 \
+      $@
+}
+
+## Look for group/sub-group's ID
+##   REF: https://docs.gitlab.com/ee/api/groups.html#search-for-group
+search_groups() {
+  gitlab_curl \
+      "https://gitlab.com/api/v4/groups/?search=${1// /%20}" \
+    | jq \
+      --compact-output \
+      --monochrome-output \
+      --raw-output \
+      '.[] | select (.web_url=="https://gitlab.com/groups/'"${1}"'") | .id'
+}
+
+## Get IDs for all (sub-)group's projects
+##   REF: https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects
+get_groups_name() {
+  gitlab_curl \
+      "https://gitlab.com/api/v4/groups/${groupID}/projects/?order_by=name&sort=asc&per_page=100&page=${1}&archived=false" \
+    | jq \
+      --compact-output \
+      --monochrome-output \
+      --raw-output \
+      '.[].name'
+}
+
+## Get all subgroups
+get_subgroups_name() {
+  ## Reset page counter
+  page=0
+
+  ## Reset
+  projects=""
+
+  ## Keep going forever
+  while true; do
+    ## Increase page counter
+    page=$((page+1))
+
+    ## Get all projects for that group's name [page amount]
+    project=$( get_groups_name "${page}" )
+
+    ## Check the response, if there isn't any more, quit
+    test -z "${project}" \
+      && break
+
+    projects=$( echo -e "${projects}\n${project}" | grep -v '^$' )
+  done
+  echo "${projects}"
+}
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+## Check for packages
+for cmd in jq curl; do
+  if ! command -v "${cmd}" 1>/dev/null 2>&1; then
+    echo "[-] Missing: ${cmd}"
+    exit 1
+  fi
+done
+
+## Read in command line arguments/options
+while [ $# -gt 0 ]; do
+  case "$1" in
+    --ssh)   auth="ssh";;
+    --https) auth="https";;
+    *)
+      echo "[-] ERROR: unsupported option: $1" >&2
+      echo "    $0 [--https|--ssh]" >&2
+      exit 1
+    ;;
+  esac
+  shift
+done
+
+if [ "${auth}" = "https" ]; then
+  url="https://gitlab.com/"
+else
+  url="git@gitlab.com:"
+fi
+
+# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+
+groupID=$( search_groups "${groupname}" )
+echo "[i] Found (sub-)group: https://gitlab.com/${groupname} (ID: ${groupID})"
+
+echo "[i] Fetching all projects"
+## Removing WIP as its Kali's way of tracking packages which are Work In Progress queue
+packages=$( get_subgroups_name "${groupID}" \
+            | grep -v "^WIP$" \
+            | sort )
+## Alt way of doing could be something like this
+## ...still would need to put the rest of the boiler template for salsa
+#packages=$( salsa \
+#                 --conf-file ./salsa.d/auth.conf \
+#                 --group-id 5034987 \
+#                 --no-archived \
+#                 ls \
+#            | awk '/Name:/ {print $2}' \
+#            | grep -v "^WIP$" \
+#            | sort )
+
+## Summary is always nice
+packages_count=$( echo "${packages}" | wc -l )
+echo "[i] Found ${packages_count} projects (https://gitlab.com/${groupname})"
+
+if [ -z "${packages}" ] \
+|| [ "${packages_count}" -lt 2 ]; then
+  echo "[-] ERROR: Unable to get any projects" 1>&2
   exit 1
 fi
 
 cat <<EOF> mrconfig
 [DEFAULT]
 jobs = 4
-# Ignore svn/cvs metadata
+
+## Ignore svn/cvs metadata
 svn_test = false
 cvs_test = false
-# Checkout the debian branch if it exists
+
+## Checkout the Debian branch if it exists
 post_checkout =
-	cd \$MR_REPO
-	if git show-ref -q --verify refs/remotes/origin/debian; then
-	    git branch --track debian origin/debian
-	fi
-# Update the 3 branches, plus the debian branch if it exists
+  cd \$MR_REPO
+  if git show-ref -q --verify refs/remotes/origin/debian; then
+    git branch --track debian origin/debian
+  fi
+
+## Update the 3 branches, plus the Debian branch if it exists
 update =
-	gbp pull
-	if git show-ref -q --verify refs/remotes/origin/debian; then
-	    if ! git show-ref -q --verify refs/heads/debian; then
-	        git branch --track debian origin/debian
-	    fi
-	    git fetch origin debian:debian
-	fi
+  gbp pull
+  if git show-ref -q --verify refs/remotes/origin/debian; then
+    if ! git show-ref -q --verify refs/heads/debian; then
+      git branch --track debian origin/debian
+    fi
+    git fetch origin debian:debian
+  fi
 EOF
 
-for project in ${projects}; do
+for package in ${packages}; do
   cat <<EOF>> mrconfig
 
-[${project}]
-checkout = gbp clone --defuse-gitattributes=off --debian-branch=kali/master git@gitlab.com:kalilinux/packages/${project}.git
+[${package}]
+checkout = gbp clone --defuse-gitattributes=off --debian-branch=${branch} ${url}${groupname}/${package}.git
 EOF
 done
+
+echo "[+] Done"
