Update usage example for bin/configure-packages

diff --git a/bin/configure-packages b/bin/configure-packages
--- a/bin/configure-packages
+++ b/bin/configure-packages
@@ -1,20 +1,41 @@
-#!/bin/sh
+#!/usr/bin/env bash
+#
+# Usage: ./bin/configure-packages <packages>
+# If no arguments, will do '--all'
+#
+
+package="${1:---all}"
+source .gitlab-token
 
 if [ ! -e ./salsa/auth.conf ] || [ ! -e ./salsa/packages.conf ]; then
-    echo "ERROR: You don't seem to be in the correct directory" >&2
-    echo "Run this tool from the top-level directory as: ./bin/configure-packages" >&2
-    exit 1
+  echo "ERROR: You don't seem to be in the correct directory" >&2
+  echo "Run this tool from the top-level directory as: ./bin/configure-packages" >&2
+  exit 1
 fi
 
-if [ ! -e ./.gitlab-token ]; then
-    echo "ERROR: You are missing ./.gitlab-token" >&2
-    echo "Create: https://gitlab.com/profile/personal_access_tokens" >&2
-    echo "Afterwards: echo \"SALSA_TOKEN='XXX'\" > ./.gitlab-token" >&2
-    exit 1
+if [ -z "${SALSA_TOKEN}" ]; then
+  echo "ERROR: You are missing ./.gitlab-token" >&2
+  echo "Create: https://gitlab.com/profile/personal_access_tokens" >&2
+  echo "Afterwards: echo \"SALSA_TOKEN='XXX'\" > ./.gitlab-token" >&2
+  exit 1
+fi
+
+if [ "${package}" = "--all" ]; then
+  # This is done, as --all would be doing BOTH --archived and --no-archived
+  # https://gitlab.com/kalilinux/packages
+  package=$(salsa --conf-file ./salsa/auth.conf \
+        --group-id 5034987 \
+        --no-archived \
+        ls \
+    | awk '/Name:/ { print $2 }' \
+    | sort)
+
+  echo "[i] No selected Package. Doing --all ($(echo "${package}" | wc -l) packages)"
 fi
 
 salsa \
   --conf-file ./salsa/auth.conf \
   --conf-file +./salsa/packages.conf \
+  --debug \
   --verbose \
-  update_safe ${1:---all} \
+  update_safe ${package}
